### ISSUE TITLE
Consider lowering the amount of ram given to elastic search

### ISSUE THREAD

**Issue by rgayon** [google/dfdewey#2]
I couldn't start the elasticsearch docker container in a cloud environment (with limited RAM) for the codelab:
```
2020-05-07T12:28:45.506740748Z # Native memory allocation (mmap) failed to map 34272509952 bytes for committing reserved memory.
```

I had to revert to more conservative values such as :
```
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
```

**Comment by dfjxs** [comment]
The memory setting was deliberately set high for performance. I've added a note to the docker-compose file and to the usage docs suggesting a lower setting for systems with limited resources.
